inployment-db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=WangBankleCrimThing78GRAH
    - POSTGRES_USER=inployer
inployment-web:
  build: .
  command: bash start.sh
  volumes:
    - .:/code
  ports:
     - "8000:8000"
  links:
     - inployment-db
