inployment-db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=WangBankleCrimThing78GRAH
    - POSTGRES_USER=inployer
inployment-web:
  build: ./inployment-django
  command: python inployment-django/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
     - "8000:8000"
  links:
     - inployment-db
