inployment-db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=WangBankleCrimThing78GRAH
    - POSTGRES_USER=inployer

inployment-web:
  dns: 8.8.8.8
  build: ./inployment-django
  volumes:
    - ./inployment-django:/code
  ports:
     - "8000:8000"
  links:
     - inployment-db
  command: /usr/local/bin/gunicorn inployment.wsgi:application -w 2 -b :8000

inployment-nginx:
  restart: always
  build: ./inployment-nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - inployment-web
  links:
    - inployment-web
