inployment-db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=WangBankleCrimThing78GRAH
    - POSTGRES_USER=inployer

inployment-web:
  build: ./inployment-django
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
    - ./inployment-django:/code
  ports:
     - "8000:8000"
  links:
     - inployment-db

inployment-nginx:
  restart: always
  build: ./inployment-nginx
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - inployment-web
  links:
    - inployment-web
